# SPDX-FileCopyrightText: 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[extend]
useDefault = true


[allowlist]
description = "Allow CI folder as it scanned separately"
paths = [
  '''ci''',
  '''gitleaks_baselines''',
]
