# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
    "**/SHA256SUM",
    "**/VERSIONS",
    "**/GOTOOLS_VERSIONS",
    "**/*.md",
    "**/go.mod*",
    "**/go.sum",
    "VERSION",
    "gitleaks_baselines/*"
]

SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
