---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Scorecard CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

# Global token permissions (least privilege)
permissions:
  contents: read       # default permission

jobs:
  call-scorecard:
    if: github.ref == 'refs/heads/main'  # only run on main
    permissions:
      security-events: write  # only this job can write security events
      contents: read          # minimal additional permission
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge-scorecard.yml@24a3a495be45af021486e265cf09a17ac3798405  # v2026.0.13
    with:
      project_folder: "."
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
