---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Scorecard CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-scorecard:
    permissions:
      security-events: write   # required for SARIF upload
      id-token: write
      contents: read

    uses: open-edge-platform/orch-ci/.github/workflows/post-merge-scorecard.yml@ed2be643a5f440a09627fef662a82a8768a1e4f7  # v2026.0.11
    with:
      project_folder: "."
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
