---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: Pre-Merge CI Pipeline
on:
  workflow_call:
    inputs:
      runner_version:
        description: "Runner version to use"
        required: true
        default: "ubuntu-24.04"
        type: string
      run_security_scans:
        description: "Run security scans"
        required: false
        default: true
        type: boolean
      run_version_check:
        description: "Run version check"
        required: false
        default: true
        type: boolean
      run_reuse_check:
        description: "Header license scan with reuse"
        required: false
        default: true
        type: boolean
      run_build:
        description: "Run build"
        required: true
        default: true
        type: boolean
      run_lint:
        description: "Run lint"
        required: false
        default: true
        type: boolean
      run_test:
        description: "Run test"
        required: false
        default: true
        type: boolean
      run_integration_test:
        description: "Run integration test"
        required: false
        default: true
        type: boolean
      run_fuzz_test:
        description: "Run fuzz test"
        required: false
        default: true
        type: boolean
      run_package_build:
        description: "Build agent package"
        required: true
        default: true
        type: boolean
      run_package_test:
        description: "Run package test"
        required: false
        default: true
        type: boolean
      run_shellcheck_common:
        description: "Run shellcheck on common scripts"
        required: false
        default: true
        type: boolean
      run_shellcheck_agent:
        description: "Run shellcheck on agent scripts"
        required: false
        default: true
        type: boolean
      prefix_tag_separator:
        description: "If provided, the tag will be prefixed input.project_folder with this separator"
        required: false
        default: ""
        type: string
      project_folder:
        description: "Project subfolder where the job will run, defaults to ."
        required: false
        default: "."
        type: string
jobs:
  run-repo-pipelines:
    runs-on: ${{ inputs.runner_version }}
    env:
      GIT_SHORT_URL: ${{ github.repository }}
      PROJECT_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history, WO sporadic issue with missing tags
          fetch-tags: true # Fetch tags
          ref: ${{ github.head_ref }} # Checkout the branch that triggered the workflow to avoid detached HEAD

      - name: REUSE Compliance Check
        if: ${{ inputs.run_reuse_check == true }}
        uses: fsfe/reuse-action@v4

      - name: Checkout action repository
        uses: actions/checkout@v4
        with:
          repository: open-edge-platform/orch-ci
          path: ci
          token: ${{ secrets.SYS_ORCH_GITHUB }}

      - name: Sanitize project folder
        run: |
          SANITIZED_REPORT_PATH=$(echo "${{ inputs.project_folder }}" | tr '/' '-')
          echo "SANITIZED_REPORT_PATH=${SANITIZED_REPORT_PATH}" >> $GITHUB_ENV

      - name: Run ClamAV Scan
        if: ${{ inputs.run_security_scans }}
        uses: open-edge-platform/orch-ci/.github/actions/clamav@40d61a820157bc9b70d3f2bdc5aec786073d48f2
        with:
          report-path: clamav_scan_report-${{ inputs.project_folder }}.txt
          project-folder: ${{ inputs.project_folder }}

      - name: Upload ClamAV Scan Report
        if: ${{ inputs.run_security_scans }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CLAMAV_ARTIFACT_NAME }}
          path: ${{ env.SANITIZED_CLAMAV_REPORT_PATH }}

      - name: Run Trivy Filesystem Scan
        if: ${{ inputs.run_security_scans }}
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: ${{ inputs.project_folder }}
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          ignore-unfixed: true
          scanners: 'vuln,misconfig,secret'
          output: "trivy_scan_report-${{ env.SANITIZED_REPORT_PATH }}.txt"

      - name: Upload Trivy Scan Report
        if: ${{ inputs.run_security_scans }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report-${{ env.SANITIZED_REPORT_PATH }}
          path: trivy_scan_report-${{ env.SANITIZED_REPORT_PATH }}.txt

      - name: Setup CI environment
        uses: open-edge-platform/orch-ci/.github/actions/bootstrap@40d61a820157bc9b70d3f2bdc5aec786073d48f2
        with:
          gh_token: ${{ secrets.SYS_ORCH_GITHUB }}

      - name: Version Check
        if: ${{ inputs.run_version_check == true }}
        env:
          BASEDIR: ${{ inputs.project_folder }}
        run: |
          if [ -n "${{ inputs.prefix_tag_separator }}" ]; then
            ./ci/scripts/version-check.sh "${{ inputs.project_folder }}${{ inputs.prefix_tag_separator }}"
          else
            ./ci/scripts/version-check.sh
          fi

      - name: Build Code
        if: ${{ (inputs.run_build == true) && (inputs.project_folder != 'common') && (inputs.project_folder != 'platform-observability-agent') && (inputs.project_folder != '') }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          echo "Building the code"
          make build

      - name: Lint Code
        if: ${{ (inputs.run_lint == true) && (inputs.project_folder != 'platform-observability-agent') && (inputs.project_folder != '') }}
        working-directory: ${{ inputs.project_folder }}
        run: |
          make lint

      - name: Test Code
        if: ${{ (inputs.run_test == true) && (inputs.project_folder != 'platform-observability-agent') && (inputs.project_folder != '') }}
        working-directory: ${{ inputs.project_folder }}
        run: |
          make unit-test

      - name: Cert setup for integration tests
        if: ${{ (inputs.project_folder == 'cluster-agent') || (inputs.project_folder == 'hardware-discovery-agent') || (inputs.project_folder == 'node-agent') }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          sudo cp test/_dummy.crt /usr/local/share/ca-certificates/_dummy.crt
          sudo update-ca-certificates

      - name: Integration test
        if: ${{ (inputs.run_integration_test == true) && (inputs.project_folder != 'common') && (inputs.project_folder != 'platform-observability-agent') && (inputs.project_folder != 'platform-update-agent') && (inputs.project_folder != '') }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          make integration_test

      - name: Fuzz test
        if: ${{ (inputs.run_integration_test == true) && (inputs.project_folder != 'common') && (inputs.project_folder != 'platform-observability-agent') && (inputs.project_folder != '') }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          make fuzztest

      - name: INBM dependency download
        if: ${{ inputs.project_folder == 'platform-update-agent' }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          make inbmdownload

      - name: POA dependency download
        if: ${{ inputs.project_folder == 'platform-observability-agent' }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          sudo make package_depends
          make download_deps

      - name: Build Package
        if: ${{ (inputs.run_package_build == true) && (inputs.project_folder != 'common') && (inputs.project_folder != '') }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          echo "Building the package"
          make package

      - name: POA dependency clean up
        if: ${{ inputs.project_folder == 'platform-observability-agent' }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          rm -rf assets

      - name: Apt update
        if: ${{ inputs.project_folder == 'platform-observability-agent' }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          sudo apt update

      - name: Package test
        if: ${{ (inputs.run_package_test == true) && (inputs.project_folder != 'common') && (inputs.project_folder != 'platform-update-agent') && (inputs.project_folder != '') }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          #make package_test
          echo "Test package"

      - name: Shellcheck common scripts
        if: ${{ (inputs.run_shellcheck_common == true) && (inputs.project_folder == 'common') }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          find . -type f -name *.sh -exec "shellcheck" "-e" "SC2010,SC2086" {} +

      - name: Shellcheck agent scripts
        if: ${{ (inputs.run_shellcheck_agent == true) && (inputs.project_folder == 'platform-observability-agent') }}
        working-directory: ${{ inputs.project_folder }}
        shell: bash
        run: |
          find scripts/ -type f -name *.sh -exec "shellcheck" {} +

      - name: Send failure email
        if: ${{ failure() }}
        run: |
          echo "Sending failure email..."
